### ISSUE TITLE
hotelReservation: segmentation fault in rate service

### ISSUE THREAD

**Issue by lianhao** [delimitrou/DeathStarBench#130]
Running current hotel reservation workload (commit id: 1e53cec) in k8s, when we use >1 replicaCount for those scalable services(frontend, search, rate, etc.), we sporadically found that rate POD would crash with the following logs:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x8b5d61]

goroutine 82 [running]:
github.com/harlow/go-micro-services/services/rate.RatePlans.Less(...)
        /go/src/github.com/harlow/go-micro-services/services/rate/server.go:185
github.com/harlow/go-micro-services/services/rate.(*RatePlans).Less(0xc4203ec2a0, 0x1, 0x0, 0x9685c0)
        <autogenerated>:1 +0x41
sort.insertionSort(0xcec1a0, 0xc4203ec2a0, 0x0, 0x2)
        /usr/local/go/src/sort/sort.go:29 +0x9c
sort.quickSort(0xcec1a0, 0xc4203ec2a0, 0x0, 0x2, 0x4)
        /usr/local/go/src/sort/sort.go:211 +0x207
sort.Sort(0xcec1a0, 0xc4203ec2a0)
        /usr/local/go/src/sort/sort.go:220 +0x79
github.com/harlow/go-micro-services/services/rate.(*Server).GetRates(0xc42011ab40, 0xcecba0, 0xc4203b6090, 0xc4203b20c0, 0x0, 0x0, 0x0)
        /go/src/github.com/harlow/go-micro-services/services/rate/server.go:168 +0xc5c
github.com/harlow/go-micro-services/services/rate/proto._Rate_GetRates_Handler.func1(0xcecba0, 0xc4203b6090, 0x9a1ac0, 0xc4203b20c0, 0xcecba0, 0xc4203b6090, 0xcf0040, 0xc420408000)
        /go/src/github.com/harlow/go-micro-services/services/rate/proto/rate.pb.go:253 +0x86
github.com/harlow/go-micro-services/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0xcecba0, 0xc4203ba1e0, 0x9a1ac0, 0xc4203b20c0, 0xc4203ec080, 0xc4203ec0a0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/harlow/go-micro-services/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:61 +0x326
github.com/harlow/go-micro-services/services/rate/proto._Rate_GetRates_Handler(0x964240, 0xc42011ab40, 0xcecba0, 0xc4203ba1e0, 0xc4203f2000, 0xc4202b4380, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/harlow/go-micro-services/services/rate/proto/rate.pb.go:255 +0x16d
github.com/harlow/go-micro-services/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc42014ac60, 0xceefe0, 0xc420100300, 0xc4203d2280, 0xc420287c80, 0xd21f00, 0x0, 0x0, 0x0)
        /go/src/github.com/harlow/go-micro-services/vendor/google.golang.org/grpc/server.go:920 +0x8f4
github.com/harlow/go-micro-services/vendor/google.golang.org/grpc.(*Server).handleStream(0xc42014ac60, 0xceefe0, 0xc420100300, 0xc4203d2280, 0x0)
        /go/src/github.com/harlow/go-micro-services/vendor/google.golang.org/grpc/server.go:1142 +0x1528
github.com/harlow/go-micro-services/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420314040, 0xc42014ac60, 0xceefe0, 0xc420100300, 0xc4203d2280)
        /go/src/github.com/harlow/go-micro-services/vendor/google.golang.org/grpc/server.go:637 +0x9f
created by github.com/harlow/go-micro-services/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
        /go/src/github.com/harlow/go-micro-services/vendor/google.golang.org/grpc/server.go:635 +0xa1

**Comment by lianhao** [comment]
This is fixed
