### ISSUE TITLE
Connection reset by peer while Registering users and constructing social graphs

### ISSUE THREAD

**Issue by Avimita-amc8313** [delimitrou/DeathStarBench#230]
I am working on the Social Network Microservices. But everytime I run: sudo python3 ./scripts/init_social_graph.py --graph=socfb-Reed98 I get this error:

Traceback (most recent call last):
  File "/home/ubuntu/DeathStarBench/socialNetwork/./scripts/init_social_graph.py", line 155, in <module>
    loop.run_until_complete(future)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/ubuntu/DeathStarBench/socialNetwork/./scripts/init_social_graph.py", line 85, in register
    _ = await asyncio.gather(*tasks)
  File "/home/ubuntu/DeathStarBench/socialNetwork/./scripts/init_social_graph.py", line 19, in upload_register
    async with session.post(addr + '/wrk2-api/user/register', data=payload) as resp:
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer

I am on a m5.4xLarge EC2 ubuntu instance.

![Screen Shot 2022-09-16 at 3 40 38 PM](https://user-images.githubusercontent.com/77707738/190717779-41b8805a-255b-4932-90ff-54e0dd1ebd07.png)

**Comment by przmk0** [comment]
can you curl Social Network main page without any issues?
